### ISSUE TITLE
Different speeds cause movement of physicals change

### ISSUE THREAD

**Issue by Belissimo-T** [seekers-dev/seekers-api#10]
`global.speed` determines `deltaT`:
https://github.com/seekers-dev/seekers-api/blob/d2707acd455bcb91e74ef80d88ed5a9f405b4362/src/main/java/org/seekers/game/Game.java#L40-L43

`deltaT` is used to compute the movement of physicals:
https://github.com/seekers-dev/seekers-api/blob/d2707acd455bcb91e74ef80d88ed5a9f405b4362/src/main/java/org/seekers/game/Physical.java#L38-L44

`deltaT` should **always** be 1 for reasons detailed below.

**Comment by Belissimo-T** [comment]
This is still the case. The `move` method can't take a `deltaT` argument. Even if, this implementation of deltaT is causing accelerations and velocities to be different if the speed is changed, not only potential collisions to be missed. 

This config option should only affect the speed at which things are simulated. In the python version this is realized by speed being the same as the simulation steps per frame.

**Comment by karl-zschiebsch** [comment]
The point is, that you really you `deltaT` to make the game faster in really slow games. But how would be this: $s=at^2+vt$? That would result in mostly the same.

**Comment by Belissimo-T** [comment]
@karl-zschiebsch 
I think we should remove the option since there is no need for it since the java version is always faster than the python AIs anyway and introducing it would make it harder for AIs predict their movement.

**Comment by karl-zschiebsch** [comment]
The point is that `deltaT` has no effect on the speed of the server, but only serves as a factor for individual processes. If, for example, you only have a little time left for testing, but you still don't want to change anything in the playing time, this feature is very important (see tournaments). As long as the python client always responds within 5 milliseconds, which is not difficult in the local network, this is not really a problem here either.

**Comment by Belissimo-T** [comment]
@joendter

**Comment by joendter** [comment]
deltaT should be a fixed variable changable in the configs
i want it to be deterministic and consistent

**Comment by Belissimo-T** [comment]
I think we are close to closing this issue! 

I think, when letting AIs compete we should always use deltaT=1 since they might rely on calculations to navigate.

Still, I would use a different formula.

**Comment by karl-zschiebsch** [comment]
To sum it up: `deltaT` stays in, but is made more realistic, and in tournaments we always use only `global.speed=1` or the `tick()` method?
