### ISSUE TITLE
Missing `global.wait-for-players` config option

### ISSUE THREAD

**Issue by Belissimo-T** [seekers-dev/seekers-api#16]
# `global.wait-for-players`
* Wait until every player has updated every of its seekers.
* This is neccessary for the game to be deterministic.

**Comment by karl-zschiebsch** [comment]
This will not be added as a optional feature, but instead the game now **always** wait for all players.

**Comment by Belissimo-T** [comment]
@karl-zschiebsch 
Does this wait every tick until all players have updated all of their seekers?
