### ISSUE TITLE
A protocol for debug graphics?

### ISSUE THREAD

**Issue by Belissimo-T** [seekers-dev/seekers-api#19]
The [python version](https://github.com/seekers-dev/seekers/blob/master/seekers/debug_drawing.py) currently supports these shapes to be drawn via debug drawing:

## Text
* text: str
* position: Vector
* color: RGB
* no size, always the same

## Line
* start: Vector
* end: Vector
* color: RGB
* width: int

## Circle
* center: Vector
* radius: float
* color: RGB
* width: int
  * if `width == 0`, the circle is filled

-------------

We need to decide if we want to support debug graphics via gRPC. I'd like to but I currently have other issues to fix. If I have time, I can propose a protocol.

**Comment by karl-zschiebsch** [comment]
The point is, that everything can and is already made by the properties and status request. I personally don´t see the point, why it would be helpfull to add another service. If you have other reasons why it would be actually helpfull, please reopen the issue

**Comment by karl-zschiebsch** [comment]
Closed with reason below
