### ISSUE TITLE
What should happen if a goal gets scored?

### ISSUE THREAD

**Issue by Belissimo-T** [seekers-dev/seekers-api#27]
The gRPC protocol only transmits changes. If a goal gets scored, however, it's ID should change (That's the specification of the original Seekers project.). This, supposedly, makes it easier for AIs to detect that a goal was scored. 

If a new goal with a new ID gets transferred, how should the client know which goal to delete?

**Comment by karl-zschiebsch** [comment]
The goal don't get deleted after all. After your goal was scored, you get a point and all properties of the goal are resetted. Your goal teleports to a new position. That method makes it just faster, because you don't need to create a new object all the time.

**Comment by Belissimo-T** [comment]
@karl-zschiebsch 

> The goal don't get deleted after all.

That means the goal's id stays the same?

**Comment by karl-zschiebsch** [comment]
Yes, exactly.
