### ISSUE TITLE
Rename this repository

### ISSUE THREAD

**Issue by Kiyotoko** [seekers-dev/seekers-api#62]
**Is your feature request related to a problem? Please describe.**
This repository is currently named `seekers-grpc`. However, the term grpc only describes the name of the library.

**Describe the solution you'd like**
Rename this repository to `seekers-api`, as this contains the definition of the api that is used for the seekers games.

**Comment by Belissimo-T** [comment]
@Kiyotoko What about `seekers-grcp-proto`?

**Comment by Kiyotoko** [comment]
@Belissimo-T I would prefer to keep the name as short as possible. Also, proto is only the file format of the files that creates the buffers and stubs for the api.
