### ISSUE TITLE
Collection of bugs and missing features

### ISSUE THREAD

**Issue by Belissimo-T** [seekers-dev/seekers-api#9]
- #8 
- AI-Name in `PlayerStatus`
- #10 
- `global.fps` property (or a different config option), python AIs can't keep up
- flag in config `global.wait-for-players`: Game waits every simulation step until all players have submitted a command
- I feeling like the collisions of seekers are blunt or inelastic, different from the Python version. But maybe I'm just wrong.
# Optional
- pulsating circles are off-center
![](https://cdn.discordapp.com/attachments/1000754865842171925/1034800854139670578/unknown.png)
- player-id instead of `camp_id` in `GoalStatus`
- typed config-Message instead of `dict[str, str]`
- debug graphics?

**Comment by joendter** [comment]
#11

**Comment by karl-zschiebsch** [comment]
Can you please write a own issue for each bug and feature, and check if with the new pushs ``command`` stills return a exception?

**Comment by Belissimo-T** [comment]
@karl-zschiebsch Okay
